---  
- name: Create resource group
  azure_rm_resourcegroup:
    name: towerdemo
    location: westeurope
- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: towerdemo
    name: myVnet
    address_prefixes: "10.0.0.0/16"
- name: Add subnet
  azure_rm_subnet:
    resource_group: towerdemo
    name: mySubnet
    address_prefix: "10.0.1.0/24"
    virtual_network: myVnet
- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: towerdemo
    allocation_method: Static
    name: myPublicIP
  register: output_ip_address
- name: Dump public IP for VM which will be created
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."
- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: towerdemo
    name: myNetworkSecurityGroup
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 1005
        direction: Inbound
- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: towerdemo
    name: myNIC
    virtual_network: myVnet
    subnet: mySubnet
    public_ip_name: myPublicIP
    security_group: myNetworkSecurityGroup
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: towerdemo
    name: myVM
    vm_size: Standard_DS1_v2
    admin_username: ec2-user
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/azureuser/.ssh/authorized_keys
        key_data: "ssh-rsa 
        AAAAB3NzaC1yc2EAAAADAQABAAABAQCt+6BmraN96zQWWXDFKWxlEOjfS2ggahCLrzYL+kFU29gEGU94wa4fOXVP/BM7bTKWwpkkusHVd8H7vngski1+xj2/PgZgLQ5ze0LGapO10wubnpzqYweJkvLiq1b+LN4ieiCR3JNgg5yFP5rGM85EkRQsW26+9VD4NR4LoghF+yxB3H1M/WC61MxtZqc+U7FjeUNPpWAYkWvstSAJbAWix9P+BJD2939cJhrKh1Kq10GzvHUQWBD3xGt9cnwsbHa00xJJMiFXwMoMJOJOh9UF9JjzV9xEtvAlnP5e/LFdN6eIx9y/lA/+qhtpdI5XCnnUIcDN017Go13UYr8NTU4j"
    network_interfaces: myNIC
    image:
      offer: RHEL
      publisher: RedHat
      sku: '7.5'
      version: latest
    tags: 
        'Group': 'webservers'
  register: azurevm  
  
- name: debug register
  debug:
    var: azurevm.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress
 
- name: Add hosts to in-memory inventory
  add_host:
    name: "{{ azurevm.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    groups: webservers
 # with_items: "{{ azurevm }}"
  
- name: Wait for SSH to come up
  wait_for:
    host: "{{ azurevm.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    port: 22 
    state: started 
  #with_items: "{{ azurevm }}"
